package com.example.goodroad.modules.tasks.data

import kotlinx.coroutines.runBlocking
import org.junit.Assert.assertEquals
import org.junit.Test

class TasksRepositoryTest {

    @Test
    fun loadTasksReturnsList() = runBlocking {
        val target = TargetViewDto(
            id = "t1",
            targetType = "PLACE",
            targetId = "101",
            title = "Shop",
            latitude = 59.0,
            longitude = 30.0,
            done = false
        )

        val task = TaskViewDto(
            id = "1",
            activityType = "WALK",
            title = "Task 1",
            points = 100,
            targetCount = 1,
            completedCount = 0,
            autoGenerated = false,
            targets = listOf(target)
        )

        val api = FakeTasksApi(tasks = listOf(task))
        val repository = TasksRepository(api)

        val result = repository.loadTasks(
            activityType = "WALK",
            latitude = 59.0,
            longitude = 30.0
        )

        assertEquals(listOf(task), result)

        assertEquals("WALK", api.activityType)
        assertEquals(59.0, api.latitude)
        assertEquals(30.0, api.longitude)
    }

    @Test
    fun loadCompletedTasksReturnsList() = runBlocking {
        val completed = CompletedTaskDto(
            id = "c1",
            taskId = "1",
            taskTitle = "Task",
            pointsAwarded = 100,
            createdAt = "2026-01-01"
        )

        val api = FakeTasksApi(completedTasks = listOf(completed))
        val repository = TasksRepository(api)

        val result = repository.loadCompletedTasks()

        assertEquals(1, result.size)
        assertEquals("c1", result[0].id)
    }

    @Test
    fun completeTargetCallsApi() = runBlocking {
        val api = FakeTasksApi()
        val repository = TasksRepository(api)

        repository.completeTarget("task1", "target1")

        assertEquals("task1", api.taskId)
        assertEquals("target1", api.targetId)
    }

    private class FakeTasksApi(
        private val tasks: List<TaskViewDto> = emptyList(),
        private val completedTasks: List<CompletedTaskDto> = emptyList()
    ) : TasksApi {

        var activityType: String? = null
        var latitude: Double? = null
        var longitude: Double? = null

        var taskId: String? = null
        var targetId: String? = null

        override suspend fun getTasks(
            activityType: String?,
            latitude: Double?,
            longitude: Double?
        ): List<TaskViewDto> {
            this.activityType = activityType
            this.latitude = latitude
            this.longitude = longitude
            return tasks
        }

        override suspend fun getCompletedTasks(): List<CompletedTaskDto> {
            return completedTasks
        }

        override suspend fun completeTarget(
            taskId: String,
            targetId: String
        ) {
            this.taskId = taskId
            this.targetId = targetId
        }
    }
}