package com.example.goodroad.modules.tasks.data

data class TargetViewDto(
    val id: String,
    val targetType: String,
    val targetId: String,
    val title: String,
    val latitude: Double?,
    val longitude: Double?,
    val done: Boolean
)

data class TaskViewDto(
    val id: String,
    val activityType: String,
    val title: String,
    val points: Int,
    val targetCount: Int,
    val completedCount: Int,
    val autoGenerated: Boolean,
    val targets: List<TargetViewDto>
)

data class CompletedTaskDto(
    val id: String,
    val taskId: String,
    val taskTitle: String,
    val pointsAwarded: Int,
    val createdAt: String
)

data class TaskTargetCreateReq(
    val targetType: String,
    val targetId: Long,
    val title: String?,
    val latitude: Double?,
    val longitude: Double?
)

data class TaskCreateReq(
    val activityType: String,
    val title: String,
    val targetCount: Int,
    val points: Int?,
    val latitude: Double?,
    val longitude: Double?,
    val targets: List<TaskTargetCreateReq>
)